parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     symfonybricks
    database_user:     [change-me]
    database_password: [change-me]

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    secret:            ThisTokenIsNotSoSecretChangeIt
